### ISSUE TITLE
Non-functional on Mac OSX El Capitan

### ISSUE THREAD

**Issue by philip-hodder** [mangecoeur/document-outline#1]
Plugin works great on my Windows laptop, but does not even appear on the MBP. Explicitly toggling on/off has no effect.

**Comment by mangecoeur** [comment]
Weird, because I actually develop this on macOSX! If you could bring up the debug console (view->developer->toggle developer tools) and see if there are any error messages in the console and paste them here.

Do you have the same plugins installed on both systems? It might be there's some conflict with another plugin...

**Comment by philip-hodder** [comment]
I don't have exactly the same plugins on each system but fairly close (which I realise is not exactly helpful for debugging - I should probably use one of the sync plugins!)

Here's the output from console (if you need me to restart, turn things on/off just let me know):

index.js:52 Window load time: 1382ms
workspace-element.coffee:13 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
deserializer-manager.js [sm]:77 No deserializer found for Object__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()
text-editor-component.coffee:733 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63 Uncaught TypeError: Invalid Point: ((64, 0), 0)
https://is.gd/create.php?format=simple Failed to load resource: the server responded with a status of 400 ()
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3256 Uncaught (in promise) Object
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:35 Uncaught TypeError: Invalid Point: ((0, 0), 0)
https://is.gd/create.php?format=simple Failed to load resource: the server responded with a status of 400 ()
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3256 Uncaught (in promise) Object

**Comment by mangecoeur** [comment]
Hum, not super enlightening. Which version of Atom are you using? The best I can think of for now is to try to uninstall and reinstall the plugin (just in case the plugin dependencies didn't load or something).

**Comment by philip-hodder** [comment]
1.11.2

Tried uninstalling and reinstalling but no joy. I'll poke around with other plugins and see what I can find.

Thanks!

**Comment by mangecoeur** [comment]
Ok super weird, your config matches mine pretty closely :/ Let me know if you find anything.

**Comment by philip-hodder** [comment]
OK, here's something. On the Mac I use the "language-markdown" plugin. On Windows I use "language-pfm" (Pandoc flavoured markdown). If I switch the Windows version to "language-markdown" then I get the same error, i.e. "document-outline" does not appear.

**Comment by philip-hodder** [comment]
atom.io seemed to be down for a while this afternoon, but finally managed to install language-pfm on the Mac and it works fine! Thanks for your help!

**Comment by mangecoeur** [comment]
Great thanks for letting me know, I will see to it that langauge-pfm is not required for the package to work

**Comment by mangecoeur** [comment]
OK that sounds like a scope activation issue I must be assuming that pfm is
being used
