### ISSUE TITLE
Only detects headings with blank line after

### ISSUE THREAD

**Issue by evanwarner** [mangecoeur/document-outline#12]
This package only seems to correctly detect headings that have a blank line after them. Headings with content on the subsequent line are ignored, and actually seem to cause the outliner to give up altogether.

Mac OSX 10.11.6
Atom 1.16.0
document-outline 1.2.0
(using language-gfm)

**Comment by mangecoeur** [comment]
Strictly, I believe headings in markdown should be followed by a blank line. To some extent this is necessary to support the different heading types (ats-style and settext/RST style). However it shouldn't crash the outliner if there are headings without spaces. Maybe you could send me some sample text i can add to the tests

**Comment by evanwarner** [comment]
I actually looked around to see if that was a requirement I didn't know about, but couldn't find a single source that claimed headings had to have a blank line following. And every MD previewer I've ever used (including this comment field) renders headings fine without subsequent blank lines.

This produces the expected outline
```
# h1

## h2

### h3

#### h4


```

This outlines nothing
```
# h1
## h2
### h3
#### h4
```

This also outlines nothing
```
# h1
Some text

## h2
Some text

### h3
Some text

#### h4
Some text
```

This outlines only **· h2**
```
# h1
## h2

### h3
#### h4
```

**Comment by mangecoeur** [comment]
Ok I published a patch for this. However I realised there is a more general issue (that was partly made easier to workaround when a blank line was required) that if you have a # in a comment (e.g. inside a code block) it comes up as a heading. Probably need more serious refactoring to fix that. Opening a separate issue.

**Comment by evanwarner** [comment]
1.3.0 works great! Thanks for the rapid updates.
