### ISSUE TITLE
1.2.1 inadvertently outlines list items

### ISSUE THREAD

**Issue by evanwarner** [mangecoeur/document-outline#14]
The 1.2.1 update now picks up headings correctly, but it's also outlining list elements in very bizarre ways.

This code
```
# h1
Some text

## h2
Some text

### h3
- item 1
  - item 1a
  - item 1b
  - item 1c
- item 2
- item 3
  - item 3a
- item 4
  - item 4a
  - item 4b
- item 5
- item 6
- item 7
- item 8
- item 9
- item 10
- item 11
- item 12
- item 13
- item 14
- item 15
- item 16
- item 17
- item 18
- item 19
- item 20
```

Produces this outline
```
▾ h1
  ▾ h2
    · h3
  · - item 1c
  · - item 3a
  · - item 4b
  · - item 6
  · - item 8
  · - item 10
  · - item 12
  · - item 14
  · - item 16
  · - item 18
```

**Comment by mangecoeur** [comment]
Ok so the solution is to require a newline after setext-style headers. I think this is just going to have to be a limitation of document outline for now. I'm thinking of replacing my home-baked heading code with a proper markdown parser, which might be a slower but more correct...
