### ISSUE TITLE
Jump to not working correct

### ISSUE THREAD

**Issue by Bersacker** [mangecoeur/document-outline#18]
I not sure whats the Problem. 
If i select an Headline it is not moving to the correct line. 
For the last 4 Headlines it jumps to the end of the Document.
is there a log? How can i check ?
(Using Latex)

**Comment by mangecoeur** [comment]
It should jump so that the heading you click on is in the middle of the screen. Perhaps you can share the document that is causing issues - I mostly test on markdown so there can be more issues in Latex.

**Comment by Bersacker** [comment]
I invited you to my privat Repo with the Documents.
The Document is Kapitel/architektur.tex
Don't want to share the Document in the Issue.

**Comment by mangecoeur** [comment]
Thanks I had a look. As far as I can tell, the behaviour is as expected - the document only scrolls to make sure the heading is on the screen - if it is already in view, the document does  not scroll. It might be possible to force the document to scroll such that the clicked heading is always at the top of the view, although I'm not sure that will be better - will look at the scrolling options in Atom

**Comment by mangecoeur** [comment]
Ok I had a look and there are actually not many options given to us by Atom.

Perhaps it will work better for you if you enable the option 'Scroll past end' under Settings -> Editor . This will enable the last headings in the document to be better centred in the window

**Comment by Bersacker** [comment]
Then the Package is broken on my End. I tested it on 2 PC's. 
If i click on "Grundsystem" the First headline that is moving is "Bereich ausblenden"
https://i.imgur.com/9SRPupy.gifv
I'm clicking on every Headline

**Comment by mangecoeur** [comment]
Hmm ok, maybe you can look at the developer console to see if there are any message View->Developer->Toggle Developer tools

**Comment by Bersacker** [comment]
No Console Output.
Can I enable DebugMode somewhere?

**Comment by mangecoeur** [comment]
There isn't really a debug mode, and I don't think you would see much anyway if there are already no errors. Quite strange... like i said it seems to work as expected for me.

**Comment by Bersacker** [comment]
I looked into it.
I think the Problem is inside lineNumberByIndex
It stops based on the index. 
The index goes up to 21189. 
The Base of the Problem seems to be the default parseLevel.
I don't have problems with Markdown. 
I think this lines
 ``` js
while ((result = regex.exec(text)) !== null) {
// allow subclasses to customise how they get level, label from regex
parsedResult = this.getRegexData(result); 
```
are the Problem. 
But I'm not into regex and js so not sure what this is doing.

**Comment by Bersacker** [comment]
The Lines are off. So I think the Problem is inside.
lineNumberByIndex.
I'm not sure was this Methode does.

**Comment by mangecoeur** [comment]
Latest version uses native buffer to get correct line numbers on atom 1.20+, should fix this.
