### ISSUE TITLE
Please add the option to toggle coloring

### ISSUE THREAD

**Issue by ungooglable** [mangecoeur/document-outline#20]
I like Atom Dark UI theme, and it's one of the default themes. It works ugly from h3 headers on. 

I saw you closed the issue 

But could you add the option in Settings to turn that header coloring off?

![document-outline-coloring](https://cloud.githubusercontent.com/assets/23142833/25496672/776e01b6-2b8a-11e7-9a30-0e1b7f4f1965.png)

**Comment by mangecoeur** [comment]
As I wrote in the closed issue, those older themes behave differently from the new ones so it's harder to correctly support both. The easiest for you would be to customize your appearance by changing the highlight color (`document-outline .highlight`) in your custom.css file.

**Comment by ungooglable** [comment]
Oh, thanks 
However it would be handy to have the option 


Надіслано із пристрою Samsung

-------- Оригінальне повідомлення --------
Від: mangecoeur <notifications@github.com> 
Дата: 2017.04.28  16:20  (GMT+02:00) 
Кому: mangecoeur/document-outline <document-outline@noreply.github.com> 
Копія: ungooglable <altacoda@gmail.com>, Author <author@noreply.github.com> 
Тема: Re: [mangecoeur/document-outline] Please add the option to toggle
  coloring (#20) 

As I wrote in the closed issue, those older themes behave differently from the new ones so it's harder to correctly support both. The easiest for you would be to customize your appearance by changing the highlight color (document-outline .highlight) in your custom.css file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mangecoeur/document-outline","title":"mangecoeur/document-outline","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mangecoeur/document-outline"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mangecoeur in #20: As I wrote in the closed issue, those older themes behave differently from the new ones so it's harder to correctly support both. The easiest for you would be to customize your appearance by changing the highlight color (`document-outline .highlight`) in your custom.css file."}],"action":{"name":"View Issue","url":"https://github.com/mangecoeur/document-outline/issues/20#issuecomment-297995674"}}}

**Comment by mangecoeur** [comment]
Done in the latest version
