### ISSUE TITLE
Feauture Request: Permanently attached outline block

### ISSUE THREAD

**Issue by LastGreenLeaf** [mangecoeur/document-outline#25]
Hello!
Right now, when you toggle plugin on, it will create an outline for a focused document. But 'on blur' the outline block will be hidden. Sometimes this behaviour uncomfortable as editor is dynamically resizing and you'll be forced to look for the place where you were (again).

Is there any way to permanently attach the outline block to the right (or left) so that it will disappear only if I toggle the plugin off? 

Update: Specify that I meant to keep the block attached even if the document is not supported for outlining.

**Comment by mangecoeur** [comment]
I will consider this when I look at porting document outline to the new Docks system coming in 1.17

**Comment by LastGreenLeaf** [comment]
@mangecoeur, OK, thanks! Looking forward to your decision on this feature.

**Comment by mangecoeur** [comment]
closed in 1.6
