### ISSUE TITLE
Is z-index required?

### ISSUE THREAD

**Issue by ethernal** [mangecoeur/document-outline#27]
Is

```css
.document-outline {
...
z-index : 2;
...
```

really required for this plugin? It conflicts with file-bookmark package. See: https://github.com/akalajzi/atom-file-bookmark/issues/21

**Comment by mangecoeur** [comment]
I will probably remove this when I get round to using the new docks system
in atom 1.17

**Comment by mangecoeur** [comment]
closed in 1.6
