### ISSUE TITLE
theme question

### ISSUE THREAD

**Issue by gwijthoff** [mangecoeur/document-outline#28]
Slightly unrelated, but what are the UI and syntax themes you're using in the `document-outline` screenshot?

**Comment by mangecoeur** [comment]
UI theme I think is just one-light, the syntax theme is also one-light, with a bunch of my own tweaks to adjust the font size and weight for the markdown headings.

**Comment by dantechguy** [comment]
Just seen the screenshot and love the UI and syntax setup! Would you be able to post the tweaks you made and the colours? Thank you! :D
