### ISSUE TITLE
"null" before and after names of subsections if header is a link 

### ISSUE THREAD

**Issue by mediapathic** [mangecoeur/document-outline#29]
Really can't say it any better than the screen shot :) 

![screen shot 2017-06-19 at 10 42 39 pm](https://user-images.githubusercontent.com/144331/27318351-b565dffe-5540-11e7-9184-1edeb059308a.png)

(for the record, the headers being a link is for the imdone package, which uses md-style links to indicate kanban-style card sections, so that's an actual use case, it's not just me being weird)

**Comment by mangecoeur** [comment]
This is working for me in version 1.6.3, added an extra check which should avoid this in theory.
