### ISSUE TITLE
switching projects with document-outline active kills tree-view

### ISSUE THREAD

**Issue by lemongrassnginger** [mangecoeur/document-outline#32]
I use [project-plus](https://atom.io/packages/project-plus) to switch between projects in atom. If I have document-outline active, switching projects kills the tree-view.

To get tree-view back I have to either restart atom, or open a markdown file (the only file type I use document-outline for) and toggle document-outline on and off. 

If document-outline is toggled off, switching projects is fine. 

If switching projects lands on a focused markdown file, switching projects seems fine.

I keep tree-view and document-outline in the same dock, in the left panel.

There are other packages that can switch projects but I haven't used them. I've heard of project-manager and project-switcher. Not sure if a similar issue affects those.

```
* Atom    : 1.18.0
* Electron: 1.3.15
* Chrome  : 52.0.2743.82
* **OS:**         Microsoft Windows 10 Enterprise
* **Misc**
    * apm  1.18.1
    * npm  3.10.10
    * node 6.9.5 ia32
    * python 3.5.2
    * git 2.10.1.windows.1
    * visual studio 
```

**Comment by mangecoeur** [comment]
Hm probably something in the show/hide logic. I personally use project-manager without issue. In theory as soon as you open an md file it should trigger the outline, but since i ported to the Docks system there might be a bug in the logic.

**Comment by mangecoeur** [comment]
Hopefully this is working now with latest visibility fixes. You can also use the outline view from Atom-IDE if that works better for you.
