### ISSUE TITLE
Clicking on link does not take you to correct place in document

### ISSUE THREAD

**Issue by danyill** [mangecoeur/document-outline#33]
I think this is a generic bug across all languages:

I find there is always an offset in any moderately long document between where I want to be and where I am when I click in the document outline.

I traced the error back to this function:

```javascript
function lineNumberByIndex(index, string) {
  // RegExp
  let line = 0;
  let match;
  let re = /(^)[\S\s]/gm;
  while ((match = re.exec(string))) {
    if (match.index > index)
      break;
    line++;
  }
  return line;
}
```

This regex `[\S\s]` does not match all lines. Specifically it does not match blank/empty lines.

I have replaced with `let re = /(^.*(\r\n|\n\r|\n|\r))|(^\r\n|^\n\r|^\n|^\r)/gm;` to ensure that newlines are picked up in a hopefully cross-platform way (surely there should be something easier) and I find it now righteously goes to the correct place in the document.

This overall method is of course not a great way to locate information. The initial parsing should capture the line number in an appropriate fashion and save us from scanning for it later in a manner which is I think error prone and doesn't cope with headings which are duplicated in the document heading structure. 

But hey, it works and something is ever so much better than nothing.

**Comment by danyill** [comment]
Interesting. Does not quite resolve this.

On Windows, I find that the original regex works quite well as long as the result is divided by two. On Linux the solution provided above works better.

```javascript
function lineNumberByIndex(index, string) {
  // RegExp
  let line = 0;
  let match;
  // let re = /(^.*(\r\n|\n\r|\n|\r))|(^\r\n|^\n\r|^\n|^\r)/gm;
  let re = /(^)[\S\s]/gm;
  while (match = re.exec(string)) {
    if (match.index > index)
      break;
    line++;
  }
  console.log(index);
  console.log(line);
  return Math.floor(line/2);
}
```

I expect resolving this in a more fundamental way is beyond me for now. Happy to test any further mods and thanks for this package @mangecoeur

**Comment by mangecoeur** [comment]
Thanks for looking into this. I mostly test on mac so i will try to look further. You are right that the best solution is to get the line number while parsing, which is done for the markdown language since there is a 'real' parser available, but no such one exists for latex. might see if there are some atom apis that do a better job.

**Comment by mangecoeur** [comment]
Latest version uses native buffer to get correct line numbers on atom 1.20+, should fix this.
