### ISSUE TITLE
Too slow for large documents?

### ISSUE THREAD

**Issue by sheljohn** [mangecoeur/document-outline#35]
Is the outline currently being updated every time the text is edited?

I am observing significant delays in the editor when this extension is enabled, especially with large documents (eg 500+ lines, font 12pt, line wrap at 130ch). Arguably this extension is only useful _for_ large documents, so I would expect a more efficient backend.

For example, instead of refreshing the outline everytime the text is edited, would you be able to [throttle it](https://remysharp.com/2010/07/21/throttling-function-calls/) perhaps, or add a command or button to update the outline manually instead of automatically?

I can program quite well with node and javascript, but never wrote an extension for Atom or worked with Electron; please let me know if I can be of any help.

**Comment by mangecoeur** [comment]
The outline should be updated every time editing stops (so when you stop typing, atom api `onDidStopChanging`). I use it for markdown with a fast laptop, although I break up my documents into parts of around 300-400 lines.

Could you state: OS, Atom version, text format (markdown, latex etc)?

There appears to still be an issue with the Latex backend which can cause slowdown over time (although i haven't figured out what's causing it).

**Comment by sheljohn** [comment]
@mangecoeur Sure thing, this is for **LaTeX** documents, and the specs are:

```
$ atom --version
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ uname -v
#37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017
$ cat /proc/version
Linux version 4.10.0-33-generic (buildd@lgw01-22) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017
```

FYI, here is the breakdown (12sec record, 8sec scripting, most of it due to `document-outline`):

![breakdown](https://user-images.githubusercontent.com/1725436/30120202-1611f898-9320-11e7-8351-5a2c4dfb1832.png)

In case you are wondering, I don't think it is my machine (hexacore, 1TB ssd, 16GB). For the moment, I changed line 125 in `document-outline.js` to [`onDidSave`](https://atom.io/docs/api/v1.19.5/TextEditor#instance-onDidSave) instead.

**Comment by mangecoeur** [comment]
@sheljohn thanks for the details especially the perf log. As I suspected, it's the latex backend. For markdown i use a 'real' parser, but latex is a bit hacked together. If you are in a hacking mood, I would welcome optmisations of this - it's can be independant of Atom since it just has to work on a text buffer/string and return heading results (heading text and line number). Although with the latest Atom there might be optimised text search APIs using Atom's native text buffer. I was planning on investigating this soon now that 1.19 is out.

**Comment by sheljohn** [comment]
I will have a look at it and also at `TextBuffer` when I have a moment. From looking at `latex-model` quickly, the regex looks massive, but it's impossible to tell without testing with these things.

**Comment by mangecoeur** [comment]
The worst bit from your trace is actually calculating the line number corresponding to a given string index (the string index being the value returned from the regex search), so might be a good place to start - although on the other hand, using a 'real' parser it might be possible to avoid this regex based hack completely.

**Comment by sheljohn** [comment]
@mangecoeur I haven't really looked yet at how you compute the line corresponding to an index, but here is some code I use on a different project, which might be useful? I haven't benchmarked it against another implementation, and I don't really know how to optimise in JS (can we preallocate arrays for example, and does this help?), but for what it's worth:

```javascript
/**
 * Find the beginning and end of each line in the input text (including empty lines).
 */
function delineate(txt) {

    // find all newlines
    var newline = [];
    var re = RegExp('[\r\n]','g');
    var match = null;
    while ( match = re.exec(txt) ) {
        newline.push({
            'idx': match.index,
            'len': match[0].length
        });
    }

    // if there is no newline at the end of file
    var last = newline[ newline.length-1 ];
    if ( (last.idx + last.len) < txt.length ) {
        newline.push({ 
            'idx': txt.length,
            'len': 0
        });
    }

    // save each line
    var lines = [];
    var offset = 0;
    for ( var i = 0; i < newline.length; i++ ) {
        lines.push({
            'start': offset,
            'end': newline[i].idx,
            'len': newline[i].idx - offset
        });
        offset = newline[i].idx + newline[i].len;
    }

    return lines;
}

/**
 * Given a set of lines and an absolute position, find the line corresponding to that position.
 */
function pos2line( lines, pos ) {
    var L = 0;
    while ( (L < lines.length) && (pos > lines[L].end) ) L++;
    return L;
}
```

**Comment by mangecoeur** [comment]
quick update - the latest atom has a (experimental) native buffer search feature, i have an initial implementation that uses it if it's detected. Would be great if you could try installing the version from master and seeing if that fixes the performance issue.

**Comment by mangecoeur** [comment]
new implementation is now released (in theory also with a faster algorithm for the original approach, although i make no guarantees), requires atom 1.20+ for the fast implementation
