### ISSUE TITLE
when a header includes a hyperlink, link text is enclosed by `null ... null`

### ISSUE THREAD

**Issue by salim-b** [mangecoeur/document-outline#36]
When a hyperlink is included in a markdown title, the document outline shows ~~`nullPrint document layoutnull`~~ `null ... null` instead of _just_ the link text `...`, see screenshot below:

![bildschirmfoto vom 2017-09-29 13-51-54](https://user-images.githubusercontent.com/20040931/31014861-62edd060-a51d-11e7-8960-e9d886026fad.png)

https://github.com/mangecoeur/document-outline/issues/29 seems closely related.

**Comment by mangecoeur** [comment]
Hi can you paste an example of the input text that causes this?

**Comment by salim-b** [comment]
> Hi can you paste an example of the input text that causes this?

I just realized that the link text is there, so this is an exaxt duplicate of https://github.com/mangecoeur/document-outline/issues/29. When I filed the issue, I didn't realize that **my link text actually was `Print document layout`** (full header was `## [Print document layout](https://tex.stackexchange.com/a/51497/144087)`) 🙈 

Sorry.

**Comment by mangecoeur** [comment]
closing in favour of #29
