### ISSUE TITLE
Option `defaultSide: left` ignored

### ISSUE THREAD

**Issue by salim-b** [mangecoeur/document-outline#37]
When I set the document outline to show on the left side by default, it still appears on the right side, see screenshot:

![bildschirmfoto vom 2017-09-29 13-49-12](https://user-images.githubusercontent.com/20040931/31015082-8db58f9e-a51e-11e7-92f1-fda7bd6f47bc.png)

**Comment by mangecoeur** [comment]
ok the view/hide logic is fiddly, but the next version should at least respect this after restarting.

**Comment by salim-b** [comment]
> ok the view/hide logic is fiddly, but the next version should at least respect this after restarting.

Works now as expected in v1.6.4 🙂 👍
