### ISSUE TITLE
Constant tree indentation

### ISSUE THREAD

**Issue by CBenghi** [mangecoeur/document-outline#43]
Hello @mangecoeur, and thanks for the good work on document-outline.

there's one aspect of the tree that confuses me: the width occupied by the different chevrons or dots is variable making the text move horizontally when expanding/contracting and for elements that have different sub-indentation levels.

Playing with the style it looks like adding the width as follows
![image](https://user-images.githubusercontent.com/5476273/31181455-44d7683e-a919-11e7-8fc2-3e6544a286cc.png)

Makes the tree more stable and (I think) a more readable hierarchy. Can you see a drawback changing the style like this?

Thanks,
Claudio

**Comment by mangecoeur** [comment]
Hey I saw your PR will check it out soon

**Comment by mangecoeur** [comment]
Looks fine, thanks!
