### ISSUE TITLE
Shows empty pane only

### ISSUE THREAD

**Issue by sm8ps** [mangecoeur/document-outline#47]
Tried version 1.6.13 on two different Linux installations. Both show an empty pane entitled "Outline" when applying to a document named 'Test.md'.

**Comment by mangecoeur** [comment]
can you show the contents of the test document?

**Comment by sm8ps** [comment]
Never mind, I was just about to say that I got it fixed (or rather un-broke it). I probably had some necessary core packages disabled (maybe language-gfm). Now all is working. Sorry for the noise! Thanks for your quick response, anyways, and the useful package in the first place!
