### ISSUE TITLE
\input and \include support for latex documents

### ISSUE THREAD

**Issue by iapapistas** [mangecoeur/document-outline#49]
Could you consider adding support for \input and \include commands for latex documents?

**Comment by mangecoeur** [comment]
Unfortunately this is not really feasible, as it would mean building out a Latex processing environment dealing with a lot more complexity. This is out of scope of what I am willing to build/support at the moment I'm afraid. I would welcome contributions for better latex support in general if you are interested.

**Comment by mangecoeur** [comment]
p.s. a fun read highlighting why I want to minimise the amount of Latex processing I get into : https://tex.stackexchange.com/questions/4201/is-there-a-bnf-grammar-of-the-tex-language

**Comment by iapapistas** [comment]
Nice I will read that! Thanks!
