### ISSUE TITLE
Use Atom-IDE outline panel

### ISSUE THREAD

**Issue by danielbayley** [mangecoeur/document-outline#51]
If the _[atom-ide-ui]_ package is active, then this package should use that rather than having 2 sperate outline view panes in the dock.

See [Atom-IDE].

[atom-ide]: http://blog.atom.io/2017/09/12/announcing-atom-ide.html
[atom-ide-ui]: https://atom.io/packages/atom-ide-ui

**Comment by mangecoeur** [comment]
I will have a look, atom-ide added a completely separate outline view for code and I don't know to what extent it's possible to support it for the text-editing use case.

**Comment by mangecoeur** [comment]
The latest development version should support the outline in atom-ide, please test

**Comment by danielbayley** [comment]
Cool. What do you mean by the latest development version? I have the latest _release_ (1.7.0), but there is no change (still creates a separate outline panel).

**Comment by mangecoeur** [comment]
@danielbayley I mean the code in the master branch on github - that hasn't been release yet because it needs some testing. It would be great if you could test this! I also need to add some code to disable the native panel when the atom ide version is available.

**Comment by mangecoeur** [comment]
should be working in latest release

**Comment by danielbayley** [comment]
@mangecoeur I just updated and tested… works well! Thanks!

**Comment by mangecoeur** [comment]
Thanks! Quick request - would you mind posting a screenshot here that I will add to the intro page?

**Comment by danielbayley** [comment]
![screenshot 12 12 15 57 24](https://user-images.githubusercontent.com/7797479/33894165-32793218-df55-11e7-9578-fef2e697b414.png)

**Comment by danielbayley** [comment]
@mangecoeur That do?

**Comment by mangecoeur** [comment]
Thanks!

Sent from Mail for Windows 10
