### ISSUE TITLE
YAML block wrongly interpreted as heading

### ISSUE THREAD

**Issue by salim-b** [mangecoeur/document-outline#52]
Just notized another YAML related bug: **The content of a YAML block contained in a Markdown document anywhere but at the beginning is wrongly interpreted as a level-2 heading if certain conditions are met**:
- the YAML block ends with `---` and not `...`
- no list contained inside the YAML block
- no blank line at the end of the YAML block

See the screenshot below for illustration:

![bug](https://user-images.githubusercontent.com/20040931/31995623-859667e0-b985-11e7-9e58-b077c0c43c06.png)

I've also created a `test.md` to easily reproduce the issue: https://gist.github.com/salim-b/65036eac1b0fbc2b54230cf3ab1e9d0e

**Comment by mangecoeur** [comment]
Hmm this one is going to be tricky, because the case you describe i think is actually valid synatx for a heading in markdown :/

**Comment by salim-b** [comment]
> Hmm this one is going to be tricky, because the case you describe i think is actually valid synatx for a heading in markdown :/

Hm, I see... I've just tried the content of the `test.md` in the [CommonMark live testing tool](http://try.commonmark.org/) and it's interpreted the same way as document-outline does. The general problem is: In Pandoc Markdown the YAML block [can stand anywhere in the document, not only at the beginning](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block). I guess this inevitably results in the ambuigity we're encountering here. 🤔

**Comment by mangecoeur** [comment]
Yeah that's the downside of a loosely-defined format like markdown. I think I'm going to have to stick with only fully supporting yaml at the front, on the basis that you can still use yaml blocks in the body as long as you terminate them with `...` . This is mostly for my sanity because I wager that if I fix one flavor of markdown I will end up breaking another.

**Comment by salim-b** [comment]
> I think I'm going to have to stick with only fully supporting yaml at the front, on the basis that you can still use yaml blocks in the body as long as you terminate them with ... . This is mostly for my sanity because I wager that if I fix one flavor of markdown I will end up breaking another.

Ok, I can live with that... and fully understand your point 😄.
I think document-outline is doing it's job very well right now and it might be a good idea anyway to stick to the CommonMark spec in the case of ambuigities like this one.
