### ISSUE TITLE
Crashing atom with LateX

### ISSUE THREAD

**Issue by dnl911** [mangecoeur/document-outline#53]
My tex-file looks as follows:

```
% !TEX root = ../main.tex

\chapter{Title}
Placeholder

\section{Title2}

\section{Title3}
\subsection{Title4}
\subsection{Title5}
```

Everytime I hit "enter" after Title3, Title4 and Title5 my atom-editor crashes. If I edit the file with another editor, so after each section or subsection there is an empty line, the crash does not occur.

**Comment by luihabl** [comment]
For me the same.

**Comment by jwoillez** [comment]
Same thing for me. Something we can do help debug the issue?

**Comment by mangecoeur** [comment]
Weird, but latex is a weird format so probably something screwy in the
regex. Will try to reproduce as a first step. What OS are you on?

**Comment by jwoillez** [comment]
In my case, macOS 10.12.6

**Comment by dnl911** [comment]
I am on Windows 10 Pro (Version 10.0.16299 Build 16299), 64 bit

**Comment by mangecoeur** [comment]
Ok, managed to reproduce, that is a spectacular crash.

**Comment by mangecoeur** [comment]
Just to note as a temporary 'escape' from the edit-crash loop, if you hit enter at the START of the next line (instead of the end of the first line) you can introduce a new blank line and the crash problem goes away. No idea why this should be the case though...

**Comment by luihabl** [comment]
If it helps, I am on macOS 10.13.1

**Comment by mangecoeur** [comment]
The development version should fix this, would be great if you could test it before i release a new version (problem was something to do with the new 'native' text buffer in latest Atom)

**Comment by dnl911** [comment]
Dev packages fixes the problem for me. Thanks!
