### ISSUE TITLE
Outline panel is always visible when opening a new window

### ISSUE THREAD

**Issue by kellerj** [mangecoeur/document-outline#54]
This is happening regardless if the current window would support outline.  Further, if I have set the outline to appear on the right, it becomes the dominant sub-tab in the right panel, hiding the project view.  (And the list of files is usually want I want to get to first.  So, I have to switch tabs or close it every time I open a new window.) . (And, I have the "Show by Default" turned off.  So, IMO, that panel should never even appear unless I request it from the command pallette.)

**Comment by mangecoeur** [comment]
This is an issue with the dock system, currently if i force hide the outline it hides all dock tabs (including ones you might want to keep open). I'm trying to figure out how to remove a single dock (the open/hide commands only seem to focus/unfocus without removing)

**Comment by mangecoeur** [comment]
So i managed to get it to the point where it will not appear until first requested, but it will stay open thereafter.
