### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollToBufferPosition' of undefined

### ISSUE THREAD

**Issue by rayapril** [mangecoeur/document-outline#59]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [document-outline](https://github.com/mangecoeur/document-outline) package 2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'scrollToBufferPosition' of undefined

```
At /Users/April/.atom/packages/document-outline/lib/outline-tree.js:94

TypeError: Cannot read property 'scrollToBufferPosition' of undefined
    at OutlineTreeView.didClick (/packages/document-outline/lib/outline-tree.js:94:11)
```

### Commands

```
     -3:01.0 core:paste (input.hidden-input)
  2x -2:53.4.0 core:copy (input.hidden-input)
     -2:51.7.0 core:paste (input.hidden-input)
     -2:49.8.0 core:backspace (input.hidden-input)
     -2:43.2.0 latex:build (input.hidden-input)
```

### Non-Core Packages

```
document-outline 2.0.1 
language-latex 1.1.1 
latex 0.49.0 
pdf-view 0.61.0 
wordcount 2.10.4 
```

**Comment by salim-b** [comment]
Just ran into this issue by clicking on a heading in the document outline. It disappeared when I disabled the option `Show By Default`. After restarting atom I couldn't reproduce the issue anymore (regardless of the state of `Show By Default`)

Why is this issue closed?
