### ISSUE TITLE
new feature: Rnw support

### ISSUE THREAD

**Issue by bdemeshev** [mangecoeur/document-outline#6]
Probably you know, that Rnw is LaTeX + R.  The plugin works well for .tex, .md, .Rmd (R + markdown), but it does not work with Rnw. I would be happier with this feature :)

**Comment by mangecoeur** [comment]
should be simple enough to add by enabling for additional scopes. I think i will also add a setting to enable for additional scopes

**Comment by mangecoeur** [comment]
What package do you use for Rnw support?

**Comment by mangecoeur** [comment]
Ok should be working now with `text.knitr` language

**Comment by bdemeshev** [comment]
Thank you!!! :)
