### ISSUE TITLE
[Feature request] Collapse or expand headings

### ISSUE THREAD

**Issue by werunom** [mangecoeur/document-outline#62]
At present, when a file is opened, the outline is presented such that all the sections and subsections are expanded. 

But, for longer documents, this is not preferable as the outline suddenly becomes dense and requires collapsing all the headings to make sense of the outline. Given this, I thought of suggesting the following features:

1. `Collapse or expand at beginning` -  can you provide a configuration to toggle how the outline should start - with all headings collapsed or expanded?

2. `Collapsing/expanding synchronous with document position` - can it be done such that depending on the position in the document, only that particular section/sub-section is expanded and the rest collapsed? When I move the cursor to a different section, automatically that section expands in the outline and the rest collapses. 

Thought of sharing these feature requests.  Thanks!

**Comment by mangecoeur** [comment]
@werunom good idea, added in latest version. There is now an 'autocollapse' option, off by default.

**Comment by werunom** [comment]
Sweet! Works great. Thanks for this :)
