### ISSUE TITLE
additive highlighting of active section makes it impossible to read

### ISSUE THREAD

**Issue by crmackay** [mangecoeur/document-outline#7]
So the active section is greyed on the sidebar, but then the active subsection is darker, and the active subsubsection is darker still...this keeps going until you can't read it at all, but even level 3 is hard to read.

![image](https://cloud.githubusercontent.com/assets/3801862/23877850/bbee6c88-081a-11e7-98f8-6c9f07e496b6.png)

Are there any ways to tweak atom settings to lightening this or invert the text color?

**Comment by mangecoeur** [comment]
What theme are you using? Some changes to Atom have caused issues on particular themes.

**Comment by crmackay** [comment]
the image above was with the Atom Light UI theme and Newbound Dark Syntax theme....

a similar (albeit) opposite effect is present using the Atom Dark UI theme:

![image](https://cloud.githubusercontent.com/assets/3801862/24867986/bf261996-1ddc-11e7-9010-5017b6d81629.png)

**Comment by mangecoeur** [comment]
Thanks, I'll see if I can get this to work better when I have time. 

It seems to be specific to using the *UI* 'Atom Light' and 'Atom Dark'  themes (not the syntax theme), so I recommend using the 'One Light' or 'One Dark' UI themes as a workaround (they are also generally better supported).

**Comment by crmackay** [comment]
cool...that looks better. I had assumed the "Atom"-named UI themes would be default and best supported...but this works. Thanks!

**Comment by mangecoeur** [comment]
yeah you'd think since they were called 'Atom' that would be the case, but no - it got changed sometime in early Atom development http://blog.atom.io/2015/02/18/one-themes.html . I think they kept them around for compatibility and then forgot about them :P

**Comment by mangecoeur** [comment]
I'm going to close this for now because there doesn't seem to be a way to keep very theme happy :/

**Comment by crmackay** [comment]
sure thing...maybe add a note in the readme, about which styles are best supported?
