### ISSUE TITLE
Turn off wrapping text in outline tree

### ISSUE THREAD

**Issue by asiloisad** [mangecoeur/document-outline#75]
Hi,

How to turn off wrapping text in outline tree? in case of long headers the wrapped text is illegible.

Sincerely,
Sebastian

**Comment by mangecoeur** [comment]
Probably the easiest is to use the outline panel from atom-ide. The
document outline package acts as an outline provider for that panel, which
has different features and view options. there isn't an easy way change it
in the standard view
