### ISSUE TITLE
left side outline option

### ISSUE THREAD

**Issue by ofgulban** [mangecoeur/document-outline#8]
Hi, great package. I was wondering whether it would be possible to add an option to make the document outline appear on the left hand side of the screen?

I think might be useful when working with long files and using preview tools because the tree view can be toggled and document outline can occupy this space next to the code. Having it on the right hand side next to the preview tab is less convenient.

**Comment by mangecoeur** [comment]
It's not impossible but could be a bit fiddly since it has to work nicely with the file tree. I don't have time right now to work on it but would welcome a PR

**Comment by mangecoeur** [comment]
Update: Atom 1.17 beta introduces Docks which might be a better fit for this feature. I plan to wait at least until 1.17 is released to see if I can use them.

**Comment by mangecoeur** [comment]
closed in 1.6
