### ISSUE TITLE
Gradual slowdown with Latex doc

### ISSUE THREAD

**Issue by ilyaminati** [mangecoeur/document-outline#9]
I'm writing a long-ish Latex doc (about 1500 lines), and after some time using the editor I start to experience typing delays. I suspect that document-outline is responsible; there are no delays if I disable this package. I'm happy to try to diagnose this further in any way that would be helpful.

**Comment by mangecoeur** [comment]
Hum I thought I fixed that,there was some memory leak before it looks like
it kicks in later rather than not at all. I'm super busy right now but if
you can figure it out I would welcome that. You can also work around this
to an extent by changing the code to update the outline on document save
instead of on every edit.

**Comment by mangecoeur** [comment]
I did a fair bit of work that should reduce the amount of data that floats around so it should use less memory. Also replaced the parsing machinery with raw regexes which should also be faster. Also merged your contributions, thanks. Closing this for now, let me know if things are better for you now.

**Comment by ilyaminati** [comment]
This is still a bug in 1.4.7. Sorry, don't mean to zombify an old ticket, let me know if you want a new one.

**Comment by mangecoeur** [comment]
Can you tell me if the memory usage of Atom when you first start up and then when you start noticing slowdowns? Also what is your Atom version?

I've addressed pretty much everything I can think of and I'm getting smooth performance in Markdown, so I'm not sure what could be wrong with the Latex support - I don't use Latex much so that doesn't get much testing.

**Comment by ilyaminati** [comment]
Atom 1.16 on OS X. I'll capture memory info at next slowdown.

**Comment by ilyaminati** [comment]
First observation: slowdowns (typing delays) used to begin shortly after I would start editing, and gradually grow worse and worse until they became intolerable. After the recent fixes, I can get a lot more work done before I notice a slowdown, but once there is a slowdown, the editor becomes unusable very quickly. Progress! 👍 

Second observation: buffer edit history may be a factor. It's by far the largest element. Is document-outline either inadvertently making buffer changes? or keeping the history around too long?

![screen shot 2017-05-03 at 8 24 37 pm](https://cloud.githubusercontent.com/assets/199182/25686870/acefa7fe-303f-11e7-86e1-776ba3897a4b.png)

**Comment by mangecoeur** [comment]
In theory, I make a point of not storing any references to the text itself exactly to avoid this sort of problem. Are you sure that it is still document-outline causing your issue? I have found a smaller issue related to highlighting the current section in the outline that will be patched soon by avoiding updating the outline if the headings don't change, but that issue didn't cause the kind of slowdowns you describe.

Can you report the memory use of atom from your system monitor before and after you get a slowdown? That could help determine if there is a memory leak.

**Comment by mangecoeur** [comment]
Closing in the hope that the more recent changes fixed slowness.

**Comment by XachaB** [comment]
I am still experiencing this bug (writing my PhD dissertation in LaTeX). I disabled all packages one by one to find out this one was the source of the problem.

**Comment by mangecoeur** [comment]
@XachaB can you tell me which is your version of Atom and the plugin? I'm pretty stumped as to where all this memory is going.

**Comment by XachaB** [comment]
Atom version 1.19.0
Plugin version 1.6.1
